version: '3.8'

services:
app:
  build:
    context: .
    dockerfile: .devcontainer/Dockerfile
  working_dir: /var/www/html
  volumes:
    - .:/var/www/html:cached
  ports:
    - "8000:8000"
  environment:
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: laravel
    DB_USERNAME: root
    DB_PASSWORD: password
    REDIS_HOST: redis
    REDIS_PASSWORD: password
    REDIS_PORT: 6379
  privileged: true
  init: true
  depends_on:
    mysql:
      condition: service_healthy
    redis:
      condition: service_healthy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 10s
      retries: 10

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "password"]
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-a", "password", "ping"]
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data: