version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8000:8000"
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - "8025:8025"
